export const ADD_EMPTY_VALUE_TO_VOCABULARY = `ADD_EMPTY_VALUE_TO_VOCABULARY`
export const ADD_EMPTY_VALUE_TO_TERM = `ADD_EMPTY_VALUE_TO_TERM`
export const ADD_EMPTY_VALUE_TO_WORK = `ADD_EMPTY_VALUE_TO_WORK`

export const ADD_TERM_TO_VOCABULARY = `ADD_TERM_TO_VOCABULARY`

export const FETCHING_ALL_VOCABULARIES = `FETCHING_ALL_VOCABULARIES`
export const FETCHING_VOCABULARY_TERMS = `FETCHING_VOCABULARY_TERMS`
export const FETCHING_WORK = `FETCHING_WORK`

export const RECEIVE_ALL_VOCABULARIES  = `RECEIVE_ALL_VOCABULARIES`
export const RECEIVE_VOCABULARY_TERMS = `RECEIVE_VOCABULARY_TERMS`
export const RECEIVE_VOCABULARY_TERMS_ERROR = `RECEIVE_VOCABULARY_TERMS_ERROR`
export const RECEIVE_WORK = `RECEIVE_WORK`

export const REMOVE_TERM_FROM_VOCABULARY = `REMOVE_TERM_FROM_VOCABULARY`

export const REMOVE_VALUE_FROM_TERM = `REMOVE_VALUE_FROM_TERM`
export const REMOVE_VALUE_FROM_WORK = `REMOVE_VALUE_FROM_WORK`
export const REMOVE_VALUE_FROM_VOCABULARY = `REMOVE_VALUE_FROM_VOCABULARY`

export const SAVED_WORK = `SAVED_WORK`
export const SAVING_WORK = `SAVING_WORK`

export const UPDATE_WORK = `UPDATE_WORK`
export const UPDATE_TERM_IN_VOCABULARY = `UPDATE_TERM_IN_VOCABULARY`
export const UPDATE_VOCABULARY = `UPDATE_VOCABULARY`
