export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
export const CLEAR_ALL_NOTIFICATIONS = 'CLEAR_ALL_NOTIFICATIONS'
export const CLEAR_STALE_NOTIFICATIONS = 'CLEAR_STALE_NOTIFICATIONS'

// notification types
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR'
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS'
