export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS'
export const RECEIVE_SEARCH_ERR = 'RECEIVE_SEARCH_ERR'
export const SEARCHING = 'SEARCHING'
export const UPDATING_SEARCH = 'UPDATING_SEARCH'
