export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS'
export const RECEIVE_SEARCH_ERROR = 'RECEIVE_SEARCH_ERROR'
export const SEARCHING = 'SEARCHING'
export const UPDATING_SEARCH = 'UPDATING_SEARCH'
