export const ADD_EMPTY_VALUE_TO_TERM = 'ADD_EMPTY_VALUE_TO_TERM'

export const BULK_EDIT_TERMS = 'BULK_EDIT_TERMS'

export const FETCHING_VOCABULARY_TERMS = 'FETCHING_VOCABULARY_TERMS'

export const RECEIVE_VOCABULARY_TERMS = 'RECEIVE_VOCABULARY_TERMS'
export const RECEIVE_VOCABULARY_TERMS_ERR = 'RECEIVE_VOCABULARY_TERMS_ERR'

export const REMOVE_VALUE_FROM_TERM = 'REMOVE_VALUE_FROM_TERM'

export const UPDATE_TERM_REQUEST = 'UPDATE_TERM_REQUEST'
export const UPDATE_TERM_RESPONSE_ERR = 'UPDATE_TERM_RESPONSE_ERR'
export const UPDATE_TERM_RESPONSE_OK = 'UPDATE_TERM_RESPONSE_OK'
