export const ADD_EMPTY_VALUE_TO_VOCABULARY = 'ADD_EMPTY_VALUE_TO_VOCABULARY'
export const ADD_TERM_TO_VOCABULARY = 'ADD_TERM_TO_VOCABULARY'
export const ADD_TERM_TO_VOCABULARY_ERR = 'ADD_TERM_TO_VOCABULARY_ERR'

export const CREATE_VOCABULARY_REQUEST = 'CREATE_VOCABULARY_REQUEST'
export const CREATE_VOCABULARY_RESPONSE_OK = 'CREATE_VOCABULARY_RESPONSE_OK'
export const CREATE_VOCABULARY_RESPONSE_ERR = 'CREATE_VOCABULARY_RESPONSE_ERR'

export const DELETE_VOCABULARY_REQUEST = 'DELETE_VOCABULARY_REQUEST'
export const DELETE_VOCABULARY_RESPONSE_OK = 'DELETE_VOCABULARY_RESPONSE_OK'
export const DELETE_VOCABULARY_RESPONSE_ERR = 'DELETE_VOCABULARY_RESPONSE_ERR'

export const FETCHING_ALL_VOCABULARIES = 'FETCHING_ALL_VOCABULARIES'
export const FETCHING_ALL_VOCABULARIES_ERR = 'FETCHING_ALL_VOCABULARIES_ERR'

export const RECEIVE_ALL_VOCABULARIES  = 'RECEIVE_ALL_VOCABULARIES'

export const REMOVE_TERM_FROM_VOCABULARY = 'REMOVE_TERM_FROM_VOCABULARY'
export const REMOVE_VALUE_FROM_VOCABULARY = 'REMOVE_VALUE_FROM_VOCABULARY'

export const UPDATE_VOCABULARY = 'UPDATE_VOCABULARY'
