export const ADD_EMPTY_VALUE_TO_WORK = 'ADD_EMPTY_VALUE_TO_WORK'

export const FETCHING_WORK = 'FETCHING_WORK'
export const FETCHING_WORK_ERROR = 'FETCHING_WORK_ERROR'

export const RECEIVE_WORK = 'RECEIVE_WORK'

export const REMOVE_VALUE_FROM_WORK = 'REMOVE_VALUE_FROM_WORK'

export const SAVED_WORK = 'SAVED_WORK'
export const SAVING_WORK = 'SAVING_WORK'

export const UPDATE_WORK = 'UPDATE_WORK'

export const WORK_NOT_FOUND_ERROR = 'WORK_NOT_FOUND_ERROR'
