const fields = {
	'id': 'ID',
	'title': 'Title',
	'creator': 'Creator',
	'creator_photographer': 'Creator - Photographer',
	'format_medium': 'Format - Medium',
	'format_size': 'Format - Size',
	'date_approximate': 'Date (Approximate)',
	'date_range': 'Date Range',
	'creator_maker': 'Creator - Maker',
	'date_original_display': 'Date - Original (Display)',
	'description_size': 'Size',
	'description_note': 'Note',
	'subject_lcsh': 'Subject (LCSH)',
	'publisher_original': 'Publisher - Original',
	'date_original': 'Date - Original',
	'format_extent': 'Extent',
	'description_condition': 'Condition',
	'description_provenance': 'Provenance',
	'description_series': 'Series',
	'identifier_itemnumber': 'Item Number',
	'publisher_digital': 'Publisher - Digital',
	'format_digital': 'Format - Digital',
	'rights_digital': 'Rights - Digital',
	'subject_ocm': 'Subject (OCM)',
	'description_critical': 'Description - Critial',
	'description_indicia': 'Indicia',
	'description_text': 'Description - Text',
	'description_inscription': 'Inscription',
	'description_ethnicity': 'Ethnicity',
	'description_citation': 'Citation',
	'coverage_location_country': 'Location - Country',
	'coverage_location': 'Location',
	'creator_company': 'Company',
	'relation_seealso': 'See Also',
	'date_image_upper': 'Date - Image (Upper)',
	'date_image_lower': 'Date - Image (Lower)',
	'title_name': 'Title - Name',
	'description_class': 'Class',
	'date_birth_display': 'Date - Birth (Display)',
	'coverage_place_birth': 'Place - Birth',
	'description_military_branch': 'Military Branch',
	'description_military_rank': 'Military Rank',
	'description_military_unit': 'Military Unit',
	'date_death_display': 'Date - Death (Display)',
	'coverage_place_death': 'Place - Death',
	'description_cause_death': 'Cause of Death',
	'description_honors': 'Honors',
	'type': 'Type',
	'contributor': 'Contributor(s)',
	'description': 'Description',
	'keyword': 'Keyword',
	'rights': 'Rights',
	'publisher': 'Publisher',
	'date_created': 'Date - Created',
	'subject': 'Subject',
	'language': 'Language',
	'identifier': 'Identifier',
	'based_near': 'Based Near',
	'related_url': 'Related URL',
	'bibliographic_citation': 'Bibliographic Citation',
	'source': 'Source',
	'date_artifact_upper': 'Date - Artifact (Upper)',
	'date_artifact_lower': 'Date - Artifact (Lower)',

	//'thumbnail_path': 'Thumbnail Path',
	//'uses_vocabulary': 'Uses Vocabulary',
}

export default fields
